spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bem-api
    data-username: root
    data-password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/bem-api
    user: root
    password: 12345678
    schemas: bem-api
    baseline-on-migrate: true